server:
  port=8282

spring:
  datasource:
    url: jdbc:mysql://192.168.66.98:3306/test
    username: root
    password: P@ssw0rd
    driver-class-name: com.mysql.jdbc.Driver
  jmx:
    enabled: false